 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/carrinhos", type: :request do
  # Carrinho. As you add validations to Carrinho, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Carrinho.create! valid_attributes
      get carrinhos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      carrinho = Carrinho.create! valid_attributes
      get carrinho_url(carrinho)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_carrinho_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      carrinho = Carrinho.create! valid_attributes
      get edit_carrinho_url(carrinho)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Carrinho" do
        expect {
          post carrinhos_url, params: { carrinho: valid_attributes }
        }.to change(Carrinho, :count).by(1)
      end

      it "redirects to the created carrinho" do
        post carrinhos_url, params: { carrinho: valid_attributes }
        expect(response).to redirect_to(carrinho_url(Carrinho.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Carrinho" do
        expect {
          post carrinhos_url, params: { carrinho: invalid_attributes }
        }.to change(Carrinho, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post carrinhos_url, params: { carrinho: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested carrinho" do
        carrinho = Carrinho.create! valid_attributes
        patch carrinho_url(carrinho), params: { carrinho: new_attributes }
        carrinho.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the carrinho" do
        carrinho = Carrinho.create! valid_attributes
        patch carrinho_url(carrinho), params: { carrinho: new_attributes }
        carrinho.reload
        expect(response).to redirect_to(carrinho_url(carrinho))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        carrinho = Carrinho.create! valid_attributes
        patch carrinho_url(carrinho), params: { carrinho: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested carrinho" do
      carrinho = Carrinho.create! valid_attributes
      expect {
        delete carrinho_url(carrinho)
      }.to change(Carrinho, :count).by(-1)
    end

    it "redirects to the carrinhos list" do
      carrinho = Carrinho.create! valid_attributes
      delete carrinho_url(carrinho)
      expect(response).to redirect_to(carrinhos_url)
    end
  end
end
