# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# database: 

default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout:  5000

development:
  <<: *default 
  database: projetosi-dev
  username: root
  password: root
  host: localhost
  pool: 5
  port: 5432
  encoding: unicode

# test:
#   <<: *default
#   database: projetosi-test
#   host:     localhost

# production:
#   <<: *default
#   database: <%= ENV['RDS_DATABASE']  %>
#   username: <%= ENV['RDS_USERNAME'] %>
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host:     <%= ENV['RDS_HOST'] %>
#   port:     5432